#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 02, 2022 10:19:48 PM +07  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
import re
import random
from tkinter.constants import *

import hiragana_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        hiragana_list = "あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわゐゑをんがぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽぁぃぅぇぉ"

        top.geometry("600x482+660+199")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Hiragana Randomizer")
        top.configure(background="#d9d9d9")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.017, rely=0.021, relheight=0.954, relwidth=0.967)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.Hiragana = tk.Message(self.Frame1)
        self.Hiragana.place(relx=0.379, rely=0.239, relheight=0.326, relwidth=0.259)
        self.Hiragana.configure(background="#ffffff")
        self.Hiragana.configure(borderwidth="10")
        self.Hiragana.configure(font="-family {Segoe UI} -size 72")
        self.Hiragana.configure(foreground="#000000")
        self.Hiragana.configure(highlightbackground="#d9d9d9")
        self.Hiragana.configure(highlightcolor="black")
        self.Hiragana.configure(justify='center')
        self.Hiragana.configure(padx="1")
        self.Hiragana.configure(pady="1")
        randomHiragana = random.choice(hiragana_list)
        self.Hiragana.configure(text=randomHiragana)
        self.Hiragana.configure(width=170)

        self.HiraganaLabel = tk.LabelFrame(self.Frame1)
        self.HiraganaLabel.place(relx=0.31, rely=0.043, relheight=0.174, relwidth=0.379)
        self.HiraganaLabel.configure(relief='groove')
        self.HiraganaLabel.configure(font="-family {Segoe UI} -size 36")
        self.HiraganaLabel.configure(foreground="black")
        self.HiraganaLabel.configure(background="#d9d9d9")

        self.Hiragana1 = tk.Label(self.HiraganaLabel)
        self.Hiragana1.place(relx=0.045, rely=0.125, height=61, width=194, bordermode='ignore')
        self.Hiragana1.configure(anchor='w')
        self.Hiragana1.configure(background="#d9d9d9")
        self.Hiragana1.configure(compound='center')
        self.Hiragana1.configure(disabledforeground="#a3a3a3")
        self.Hiragana1.configure(font="-family {Segoe UI} -size 30")
        self.Hiragana1.configure(foreground="#000000")
        self.Hiragana1.configure(text='''Hiragana''')

        self.Answer = tk.Text(self.Frame1)
        self.Answer.place(relx=0.052, rely=0.696, relheight=0.261, relwidth=0.431)
        self.Answer.configure(background="white")
        self.Answer.configure(font="-family {Segoe UI} -size 48")
        self.Answer.configure(foreground="black")
        self.Answer.configure(highlightbackground="#d9d9d9")
        self.Answer.configure(highlightcolor="black")
        self.Answer.configure(insertbackground="black")
        self.Answer.configure(selectbackground="blue")
        self.Answer.configure(selectforeground="white")
        self.Answer.configure(wrap="none")

        def onsubmit(e):
            input = self.Answer.get("1.0",END)
            input = re.sub('\s+',' ',input)
            randomHiragana = random.choice(hiragana_list)
            self.Hiragana.configure(text=randomHiragana)
            return 'break'
        self.Answer.bind("<Return>", onsubmit)

        self.Result = tk.Text(self.Frame1)
        self.Result.place(relx=0.515, rely=0.696, relheight=0.261, relwidth=0.431)
        self.Result.configure(background="white")
        self.Result.configure(font="-family {Segoe UI} -size 48")
        self.Result.configure(foreground="black")
        self.Result.configure(highlightbackground="#d9d9d9")
        self.Result.configure(highlightcolor="black")
        self.Result.configure(insertbackground="black")
        self.Result.configure(selectbackground="blue")
        self.Result.configure(selectforeground="white")
        self.Result.configure(state='disabled')
        self.Result.configure(wrap="word")

        self.AnswerLabel = tk.Label(self.Frame1)
        self.AnswerLabel.place(relx=0.052, rely=0.587, height=41, width=114)
        self.AnswerLabel.configure(anchor='w')
        self.AnswerLabel.configure(background="#d9d9d9")
        self.AnswerLabel.configure(compound='left')
        self.AnswerLabel.configure(disabledforeground="#a3a3a3")
        self.AnswerLabel.configure(font="-family {Segoe UI} -size 24")
        self.AnswerLabel.configure(foreground="#000000")
        self.AnswerLabel.configure(text='''Answer''')

        self.ResultLabel = tk.Label(self.Frame1)
        self.ResultLabel.place(relx=0.517, rely=0.587, height=41, width=114)
        self.ResultLabel.configure(activebackground="#f9f9f9")
        self.ResultLabel.configure(activeforeground="black")
        self.ResultLabel.configure(anchor='w')
        self.ResultLabel.configure(background="#d9d9d9")
        self.ResultLabel.configure(compound='left')
        self.ResultLabel.configure(disabledforeground="#a3a3a3")
        self.ResultLabel.configure(font="-family {Segoe UI} -size 24")
        self.ResultLabel.configure(foreground="#000000")
        self.ResultLabel.configure(highlightbackground="#d9d9d9")
        self.ResultLabel.configure(highlightcolor="black")
        self.ResultLabel.configure(text='''Result''')


def start_up():
    hiragana_support.main()

if __name__ == '__main__':
    hiragana_support.main()




